---
spring:
  output:
    ansi:
      enabled: always
  application:
    name: java11-sb-cardatabase
---
logging:
  level:
    org.stockservice: DEBUG
---
server:
  port: 9031
---
spring:
  datasource:
    url: jdbc:h2:mem:cardb
    driver: org.h2.Driver
    username: mick
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      basePath: /api

